version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    volumes:
      - db:/data
  cache:
    image: 'redislabs/redismod:edge'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisearch.so
        --loadmodule /usr/lib/redis/modules/rejson.so
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  db:
    driver: local
  cache:
    driver: local